# Generated by Django 3.1 on 2020-08-10 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cardetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carname', models.CharField(max_length=64)),
                ('location', models.CharField(max_length=15)),
                ('year', models.PositiveIntegerField()),
                ('Kmdriven', models.PositiveIntegerField()),
                ('fuel', models.CharField(choices=[('Diesel', 'Diesel'), ('Petrol', 'Petrol'), ('CNG', 'CNG'), ('LPG', 'LPG')], max_length=256)),
                ('transmission', models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual')], max_length=256)),
                ('owner', models.CharField(choices=[('First', 'First owner of car'), ('Second', 'Second owner of car'), ('Third', 'Third owner'), ('Fourth & Above', 'Fourth & Above')], max_length=256)),
                ('mileage', models.CharField(max_length=15)),
                ('engine', models.CharField(max_length=10)),
                ('power', models.CharField(max_length=10)),
                ('seats', models.PositiveSmallIntegerField()),
                ('boughtat', models.PositiveIntegerField()),
            ],
        ),
    ]
